name: Daily Runner Keep-Alive 🚀

on:
  schedule:
    - cron: "0 14 * * *"  # 22:00 UTC+8 → 14:00 UTC
  workflow_dispatch: # Allows manual execution

jobs:
  keep-runner-alive:
    runs-on: wsl-ubuntu
    steps:
      - name: Keep Runner Active
        run: echo "Runner executing at 22:00 UTC+8"